aten._foreach_add.List: timm_train/xcit_large_24_p8_224_train.json
aten._foreach_sqrt.default: hf_train/YituTechConvBert_train.json
aten._log_softmax.default: timm_train/xcit_large_24_p8_224_train.json
aten._log_softmax_backward_data.default: timm_train/xcit_large_24_p8_224_train.json
aten._softmax.default: timm_train/xcit_large_24_p8_224_train.json
aten._softmax_backward_data.default: timm_train/xcit_large_24_p8_224_train.json
aten._unsafe_view.default: timm_train/xcit_large_24_p8_224_train.json
aten.add.Tensor: timm_train/xcit_large_24_p8_224_train.json
aten.addmm.default: timm_train/xcit_large_24_p8_224_train.json
aten.bmm.default: timm_train/xcit_large_24_p8_224_train.json
aten.div.Scalar: timm_train/visformer_small_train.json
aten.div.Tensor: timm_train/xcit_large_24_p8_224_train.json
aten.embedding.default: hf_train/YituTechConvBert_train.json
aten.embedding_dense_backward.default: hf_train/YituTechConvBert_train.json
aten.eq.Scalar: timm_train/xcit_large_24_p8_224_train.json
aten.gelu.default: timm_train/xcit_large_24_p8_224_train.json
aten.gelu_backward.default: timm_train/xcit_large_24_p8_224_train.json
aten.gt.Scalar: hf_train/T5Small_train.json
aten.masked_fill.Scalar: hf_train/T5Small_train.json
aten.masked_fill_.Scalar: timm_train/xcit_large_24_p8_224_train.json
aten.mean.dim: timm_train/visformer_small_train.json
aten.mm.default: timm_train/xcit_large_24_p8_224_train.json
aten.mul.Scalar: timm_train/resmlp_12_224_train.json
aten.mul.Tensor: timm_train/xcit_large_24_p8_224_train.json
aten.native_dropout.default: hf_train/YituTechConvBert_train.json
aten.native_dropout_backward.default: hf_train/YituTechConvBert_train.json
aten.neg.default: timm_train/xcit_large_24_p8_224_train.json
aten.nll_loss2d_backward.default: torchbench_train/pytorch_unet_train.json
aten.nll_loss2d_forward.default: torchbench_train/pytorch_unet_train.json
aten.nll_loss_backward.default: timm_train/xcit_large_24_p8_224_train.json
aten.nll_loss_forward.default: timm_train/xcit_large_24_p8_224_train.json
aten.repeat.default: timm_train/xcit_large_24_p8_224_train.json
aten.select_backward.default: timm_train/xcit_large_24_p8_224_train.json
aten.std.correction: torchbench_train/BERT_pytorch_train.json
aten.sub.Tensor: timm_train/poolformer_m36_train.json
aten.sum.dim_IntList: timm_train/xcit_large_24_p8_224_train.json
aten._to_copy.default: timm_train/xcit_large_24_p8_224_train.json
aten.abs.default: hf_train/T5Small_train.json
aten.add_.Tensor: timm_train/xcit_large_24_p8_224_train.json
aten.cat.default: timm_train/xcit_large_24_p8_224_train.json
aten.convolution.default: timm_train/xcit_large_24_p8_224_train.json
aten.convolution_backward.default: timm_train/xcit_large_24_p8_224_train.json
aten.copy_.default: timm_train/twins_pcpvt_base_train.json
aten.cudnn_batch_norm.default: timm_train/xcit_large_24_p8_224_train.json
aten.cudnn_batch_norm_backward.default: timm_train/xcit_large_24_p8_224_train.json
aten.index.Tensor: timm_train/swin_base_patch4_window7_224_train.json
aten.leaky_relu_.default: timm_train/cspdarknet53_train.json
aten.leaky_relu_backward.default: timm_train/cspdarknet53_train.json
aten.mse_loss.default: torchbench_train/tacotron2_train.json
aten.mse_loss_backward.default: torchbench_train/tacotron2_train.json
aten.native_batch_norm.default: timm_train/nfnet_l0_train.json
aten.native_batch_norm_backward.default: timm_train/nfnet_l0_train.json
aten.new_empty_strided.default: timm_train/twins_pcpvt_base_train.json
aten.new_zeros.default: timm_train/swin_base_patch4_window7_224_train.json
aten.reflection_pad2d.default: torchbench_train/pytorch_CycleGAN_and_pix2pix_train.json
aten.reflection_pad2d_backward.default: torchbench_train/pytorch_CycleGAN_and_pix2pix_train.json
aten.relu_.default: timm_train/volo_d1_224_train.json
aten.rsub.Scalar: timm_train/convit_base_train.json
aten.sgn.default: torchbench_train/timm_efficientdet_train.json
aten.sum.default: timm_train/dm_nfnet_f0_train.json
aten.tanh.default: hf_train/MT5ForConditionalGeneration_train.json
aten.tanh_backward.default: hf_train/MT5ForConditionalGeneration_train.json
aten.threshold_backward.default: timm_train/volo_d1_224_train.json
aten.upsample_bilinear2d.default: torchbench_train/vision_maskrcnn_train.json
aten.upsample_bilinear2d_backward.default: torchbench_train/pytorch_unet_train.json
aten.avg_pool2d.default: timm_train/volo_d1_224_train.json
aten.pixel_shuffle.default: torchbench_train/LearningToPaint_train.json
aten.pow.Tensor_Scalar: timm_train/convit_base_train.json
aten.relu.default: timm_train/regnety_002_train.json
aten.sigmoid.default: timm_train/tinynet_a_train.json
aten.avg_pool2d_backward.default: timm_train/volo_d1_224_train.json
aten.grid_sampler_2d.default: torchbench_train/Super_SloMo_train.json
aten.grid_sampler_2d_backward.default: torchbench_train/Super_SloMo_train.json
aten.leaky_relu.default: torchbench_train/pytorch_stargan_train.json
aten.max_pool2d_with_indices.default: timm_train/swsl_resnext101_32x16d_train.json
aten.max_pool2d_with_indices_backward.default: timm_train/swsl_resnext101_32x16d_train.json
aten.mean.default: torchbench_train/yolov3_train.json
aten.sigmoid_backward.default: timm_train/tinynet_a_train.json
aten.slice_backward.default: timm_train/xcit_large_24_p8_224_train.json
aten.stack.default: timm_train/xcit_large_24_p8_224_train.json
aten._adaptive_avg_pool2d.default: torchbench_train/vgg16_train.json
aten._adaptive_avg_pool2d_backward.default: torchbench_train/vgg16_train.json
aten.clone.default: timm_train/xcit_large_24_p8_224_train.json
aten.eq.Tensor: hf_train/XGLMForCausalLM_train.json
aten.gather.default: hf_train/PLBartForConditionalGeneration_train.json
aten.index_add.default: hf_train/XLNetLMHeadModel_train.json
aten.index_select.default: hf_train/XLNetLMHeadModel_train.json
aten.scatter.value: torchbench_train/timm_efficientdet_train.json
aten.scatter_add.default: torchbench_train/hf_Reformer_train.json
aten.scatter_reduce_.two: torchbench_train/basic_gnn_edgecnn_train.json
aten.ne.Tensor: torchbench_train/hf_Reformer_train.json
aten.pow_.Scalar: torchbench_train/basic_gnn_gcn_train.json
aten.scatter_add_.default: torchbench_train/basic_gnn_sage_train.json
aten.clamp.default: hf_train/RobertaForQuestionAnswering_train.json
aten.new_ones.default: hf_train/AllenaiLongformerBase_train.json
aten.any.default: hf_train/YituTechConvBert_train.json
aten.cumsum.default: hf_train/RobertaForQuestionAnswering_train.json
aten.fill_.Scalar: torchbench_train/vision_maskrcnn_train.json
aten.max.dim: timm_train/volo_d1_224_train.json
aten.mul_.Tensor: timm_train/dm_nfnet_f0_train.json
aten.nan_to_num.default: torchbench_train/cm3leon_generate_train.json
aten.native_layer_norm.default: timm_train/xcit_large_24_p8_224_train.json
aten.ne.Scalar: hf_train/RobertaForQuestionAnswering_train.json
aten.triu.default: hf_train/T5Small_train.json
aten.binary_cross_entropy.default: torchbench_train/dcgan_train.json
aten.binary_cross_entropy_backward.default: torchbench_train/dcgan_train.json
aten._cudnn_rnn.default: torchbench_train/tts_angular_train.json
aten._cudnn_rnn_backward.default: torchbench_train/tts_angular_train.json
aten.glu.default: torchbench_train/demucs_train.json
aten.glu_backward.default: torchbench_train/demucs_train.json
aten.sort.default: torchbench_train/moco_train.json
aten.all.default: hf_train/RobertaForQuestionAnswering_train.json
aten.all.dim: torchbench_train/detectron2_maskrcnn_r_50_fpn_train.json
aten.argmax.default: hf_train/GPTNeoForSequenceClassification_train.json
aten.binary_cross_entropy_with_logits.default: torchbench_train/yolov3_train.json
aten.bitwise_and.Tensor: torchbench_train/vision_maskrcnn_train.json
aten.clamp_.default: torchbench_train/torch_multimodal_clip_train.json
aten.constant_pad_nd.default: timm_train/tf_mixnet_l_train.json
aten.exp.default: torchbench_train/yolov3_train.json
aten.ge.Scalar: timm_train/xcit_large_24_p8_224_train.json
aten.index_put.default: timm_train/swin_base_patch4_window7_224_train.json
aten.index_put_.default: torchbench_train/yolov3_train.json
aten.log.default: hf_train/T5Small_train.json
aten.lt.Scalar: hf_train/XGLMForCausalLM_train.json
aten.max.default: torchbench_train/yolov3_train.json
aten.maximum.default: hf_train/XGLMForCausalLM_train.json
aten.minimum.default: hf_train/T5Small_train.json
aten.new_full.default: torchbench_train/vision_maskrcnn_train.json
aten.nonzero.default: torchbench_train/vision_maskrcnn_train.json
aten.prod.dim_int: torchbench_train/yolov3_train.json
aten.repeat_interleave.Tensor: torchbench_train/detectron2_maskrcnn_r_50_fpn_train.json
aten.rsqrt.default: hf_train/T5Small_train.json
aten.scatter_.value: torchbench_train/pytorch_unet_train.json
aten.topk.default: torchbench_train/vision_maskrcnn_train.json
aten.unbind.int: timm_train/xcit_large_24_p8_224_train.json
aten.unsqueeze_.default: torchbench_train/hf_BigBird_train.json
aten.where.self: timm_train/xcit_large_24_p8_224_train.json
aten.div.Tensor_mode: timm_train/xcit_large_24_p8_224_train.json
aten.floor.default: torchbench_train/vision_maskrcnn_train.json
aten.log2.default: torchbench_train/vision_maskrcnn_train.json
aten.sqrt.default: hf_train/DebertaV2ForQuestionAnswering_train.json
aten.upsample_nearest2d.default: timm_train/hrnet_w18_train.json
aten.upsample_nearest2d_backward.default: timm_train/hrnet_w18_train.json
aten.bitwise_not.default: hf_train/DebertaV2ForQuestionAnswering_train.json
aten.div_.Scalar: torchbench_train/yolov3_train.json
aten._embedding_bag.default: torchbench_train/dlrm_train.json
aten._embedding_bag_backward.default: torchbench_train/dlrm_train.json
aten._sparse_coo_tensor_with_dims_and_tensors.default: torchbench_train/dlrm_train.json
aten.bernoulli.default: torchbench_train/fastNLP_Bert_train.json
aten.bitwise_xor.Tensor: torchbench_train/fastNLP_Bert_train.json
aten.erf.default: torchbench_train/fastNLP_Bert_train.json
aten.flip.default: hf_train/AllenaiLongformerBase_train.json
aten.fmod.Scalar: torchbench_train/fastNLP_Bert_train.json
aten.lt.Tensor: hf_train/XGLMForCausalLM_train.json
aten.native_layer_norm_backward.default: timm_train/xcit_large_24_p8_224_train.json
aten.clamp_min.default: timm_train/xcit_large_24_p8_224_train.json
aten.linalg_vector_norm.default: timm_train/xcit_large_24_p8_224_train.json
aten.native_group_norm.default: timm_train/poolformer_m36_train.json
aten.new_empty.default: timm_train/swin_base_patch4_window7_224_train.json
aten.reciprocal.default: hf_train/XLNetLMHeadModel_train.json
aten.reciprocal_.default: torchbench_train/functorch_dp_cifar10_train.json
aten.sub.Scalar: torchbench_train/functorch_dp_cifar10_train.json
aten.mul_.Scalar: torchbench_train/maml_omniglot_train.json
aten.sub_.Tensor: torchbench_train/maml_omniglot_train.json
aten._scaled_dot_product_efficient_attention.default: timm_train/xcit_large_24_p8_224_train.json
aten._scaled_dot_product_efficient_attention_backward.default: timm_train/xcit_large_24_p8_224_train.json
aten.fill_.Tensor: hf_train/XGLMForCausalLM_train.json
aten.split.Tensor: timm_train/res2next50_train.json
aten.div_.Tensor: timm_train/swin_base_patch4_window7_224_train.json
aten.index_add_.default: hf_train/AllenaiLongformerBase_train.json
aten.tril.default: hf_train/AllenaiLongformerBase_train.json
aten.bernoulli_.float: timm_train/swin_base_patch4_window7_224_train.json
aten.logsumexp.default: torchbench_train/hf_Reformer_train.json
aten.remainder.Scalar: hf_train/GPTNeoForSequenceClassification_train.json
aten.scatter_.src: torchbench_train/hf_Reformer_train.json
aten.gt.Tensor: hf_train/T5Small_train.json
aten.split_with_sizes.default: timm_train/tf_mixnet_l_train.json
aten.squeeze_.dims: torchbench_train/lennard_jones_train.json
aten.hardtanh_.default: timm_train/mobilenetv2_100_train.json
aten.hardtanh_backward.default: timm_train/rexnet_100_train.json
aten._fused_moving_avg_obs_fq_helper.default: torchbench_train/resnet50_quantized_qat_train.json
aten.random_.to: timm_train/xcit_large_24_p8_224_train.json
aten.hardsigmoid.default: timm_train/mobilenetv3_large_100_train.json
aten.hardsigmoid_backward.default: timm_train/mobilenetv3_large_100_train.json
aten.hardswish_.default: timm_train/mobilenetv3_large_100_train.json
aten.hardswish_backward.default: timm_train/mobilenetv3_large_100_train.json
aten.mul.out: torchbench_train/moco_train.json
aten.random_.default: torchbench_train/moco_train.json
aten.elu.default: torchbench_train/nvidia_deeprecommender_train.json
aten.elu_backward.default: torchbench_train/nvidia_deeprecommender_train.json
aten.native_group_norm_backward.default: timm_train/poolformer_m36_train.json
aten.zero_.default: torchbench_train/tacotron2_train.json
aten._amp_update_scale_.default: torchbench_train/pytorch_unet_train.json
aten.dot.default: torchbench_train/pytorch_unet_train.json
aten._is_all_true.default: torchbench_train/soft_actor_critic_train.json
aten.le.Scalar: torchbench_train/yolov3_train.json
aten.normal.Tensor_Tensor: torchbench_train/soft_actor_critic_train.json
aten.normal_.default: torchbench_train/soft_actor_critic_train.json
aten.softplus.default: torchbench_train/soft_actor_critic_train.json
aten.softplus_backward.default: torchbench_train/soft_actor_critic_train.json
aten.masked_scatter.default: torchbench_train/speech_transformer_train.json
aten.masked_select.default: torchbench_train/speech_transformer_train.json
aten._cudnn_rnn_flatten_weight.default: torchbench_train/tts_angular_train.json
aten._pack_padded_sequence.default: torchbench_train/tacotron2_train.json
aten._thnn_fused_lstm_cell.default: torchbench_train/tacotron2_train.json
aten._thnn_fused_lstm_cell_backward_impl.default: torchbench_train/tacotron2_train.json
aten._foreach_norm.Scalar: torchbench_train/timm_efficientdet_train.json
aten.silu_.default: timm_train/tinynet_a_train.json
aten.silu_backward.default: timm_train/tinynet_a_train.json
aten.addcdiv_.default: torchbench_train/torch_multimodal_clip_train.json
aten.addcmul_.default: torchbench_train/tts_angular_train.json
aten.lerp_.Scalar: torchbench_train/torch_multimodal_clip_train.json
aten.clamp_min_.default: torchbench_train/tts_angular_train.json
aten.bitwise_or.Tensor: torchbench_train/vision_maskrcnn_train.json
aten.le.Tensor: torchbench_train/vision_maskrcnn_train.json
aten.round.default: torchbench_train/vision_maskrcnn_train.json
aten.smooth_l1_loss.default: torchbench_train/vision_maskrcnn_train.json
aten.smooth_l1_loss_backward.default: torchbench_train/vision_maskrcnn_train.json
aten.uniform_.default: torchbench_train/vision_maskrcnn_train.json
aten.add.Scalar: torchbench_train/yolov3_train.json
aten._foreach_pow.ScalarAndTensor: hf_train/YituTechConvBert_train.json
aten.masked_fill.Tensor: hf_train/DebertaV2ForQuestionAnswering_train.json
aten._fft_c2c.default: hf_train/GoogleFnet_train.json
aten.cos.default: timm_train/xcit_large_24_p8_224_train.json
aten.pow.Scalar: timm_train/xcit_large_24_p8_224_train.json
aten.sin.default: timm_train/xcit_large_24_p8_224_train.json
aten.col2im.default: timm_train/volo_d1_224_train.json
aten.im2col.default: timm_train/volo_d1_224_train.json
aten.as_strided_.default: timm_train/jx_nest_base_train.json
aten.upsample_bicubic2d.default: timm_train/crossvit_9_240_train.json
aten.unfold_backward.default: timm_train/eca_halonext26ts_train.json
aten.silu.default: timm_train/nfnet_l0_train.json
aten._safe_softmax.default: timm_train/jx_nest_base_train.json
aten.hardswish.default: timm_train/levit_128_train.json
aten.addcmul.default: timm_train/resmlp_12_224_train.json
aten.hardtanh.default: timm_train/rexnet_100_train.json
aten.roll.default: timm_train/swin_base_patch4_window7_224_train.json
aten.scatter.src: timm_train/volo_d1_224_train.json
