name: linux-benchmark-mi350
on:
  workflow_call:
    secrets:
      TRITONBENCH_SCRIBE_GRAPHQL_ACCESS_TOKEN:
        required: True
        description: |
          Tritonbench Scribe Graph Access Token
    inputs:
      benchmark_name:
        required: True
        type: string
        description: |
          Benchmark name
      conda_env:
        required: True
        type: string
        description: |
          Conda environment to activate when testing Triton
      side_a_triton:
        required: False
        type: string
        description: |
          Triton repo name
      side_a_commit:
        required: False
        type: string
        description: |
          Triton repo commit

jobs:
  linux-benchmark-mi350:
    if: github.repository_owner == 'meta-pytorch'
    runs-on: [amd-mi350-runner]
    timeout-minutes: 240
    environment: docker-s3-upload
    permissions:
      id-token: write
      contents: read
    env:
      SETUP_SCRIPT: "/workspace/setup_instance.sh"
      CONDA_ENV: ${{ inputs.conda_env }}
      RUNNER_TYPE: "amd-mi350-runner"
      DOCKER_IMAGE: "ghcr.io/meta-pytorch/tritonbench:rocm-latest"
      JOB_NAME: tritonbench-mi350-${{ inputs.conda_env }}-${{ inputs.benchmark_name }}
      TRITONBENCH_SCRIBE_GRAPHQL_ACCESS_TOKEN: ${{ secrets.TRITONBENCH_SCRIBE_GRAPHQL_ACCESS_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout Tritonbench
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::308535385114:role/gha_workflow_upload-benchmark-results
          # The max duration enforced by the server side
          role-duration-seconds: 18000
          aws-region: us-east-1
      - name: Setup uploader dependencies
        run: |
          sudo apt-get install -y python3-pip
          pip3 install -r .ci/upload/requirements.txt
      - name: Pull docker image
        uses: pytorch/test-infra/.github/actions/pull-docker-image@main
        with:
          docker-image: ${{ env.DOCKER_IMAGE }}
      - name: Start docker container
        run: |
          set -eux
          
          GPU_FLAG="--device /dev/kfd --device /dev/dri --security-opt seccomp=unconfined "

          container_name=$(docker run \
            ${GPU_FLAG:-} \
            -e CONDA_ENV \
            --ipc=host \
            --tty \
            --detach \
            --security-opt seccomp=unconfined \
            --shm-size=32g \
            --cap-add=SYS_PTRACE \
            --user root \
            -v "${GITHUB_WORKSPACE}:/tmp/workspace" \
            -w /tmp/workspace \
            "${DOCKER_IMAGE}"
          )

          # write container id to env
          echo "TRITONBENCH_CONTAINER_ID=${container_name}" >> $GITHUB_ENV
      - name: Compile Triton (On Demand)
        if: ${{ inputs.side_a_triton && inputs.side_a_commit }}
        run: |
          docker exec -t -w /tmp/workspace "${TRITONBENCH_CONTAINER_ID}" bash -c "
            set -eux
            bash ./.ci/triton/install.sh --repo ${{ inputs.side_a_triton }} --commit ${{ inputs.side_a_commit }} --side a
          "
      - name: Benchmarking
        run: |
          set -eux
          if [ -n "${{ inputs.side_a_triton }}" ] && [ -n "${{ inputs.side_a_commit }}" ]; then
            docker exec -t -w /tmp/workspace "${TRITONBENCH_CONTAINER_ID}" bash -c "
              set -eux
              bash .ci/tritonbench/run-benchmark.sh ${{ inputs.benchmark_name }} --conda-env triton-side-a
            "
          else
            docker exec -t -w /tmp/workspace "${TRITONBENCH_CONTAINER_ID}" bash -c "
              set -eux
              bash .ci/tritonbench/run-benchmark.sh ${{ inputs.benchmark_name }}
            "
          fi
          cp -r ".benchmarks/${{ inputs.benchmark_name }}" benchmark-output
          # post-process result.json
          latest_result_json=$(find ./benchmark-output -name "result.json"  | sort -r | head -n 1)
          python3 ./.ci/test_infra/oss_ci_benchmark_v3.py --json ${latest_result_json} \
            --add-github-env --output ${latest_result_json}
      - name: Upload result to GH Actions Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.JOB_NAME }}
          path: benchmark-output/
      - name: Upload result to Scribe
        run: |
          latest_result_json=$(find ./benchmark-output -name "result.json"  | sort -r | head -n 1)
          python3 ./.ci/upload/scribe.py --json ${latest_result_json}
      - name: Rewrite Tritonbench json to ClickHouse style
        run: |
          latest_result_json=$(find ./benchmark-output -name "result.json"  | sort -r | head -n 1)
          python3 ./.ci/test_infra/oss_ci_benchmark_v3.py --json ${latest_result_json} \
                 --output benchmark-output/results/result.json
      - name: Upload result to ClickHouse
        uses: pytorch/test-infra/.github/actions/upload-benchmark-results@main
        with:
          benchmark-results-dir: benchmark-output/results
          dry-run: false
          schema-version: v3
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Kill the container
        if: always()
        run: |
          docker kill "${TRITONBENCH_CONTAINER_ID}" || true
